In [1]:
import tensorflow as tf

In [2]:
# Create TensorFlow object called tensor
hello_constant = tf.constant('Hello World!')

with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant)
    print(output)

b'Hello World!'


In [3]:
# A is a 0-dimensional int32 tensor
A = tf.constant(1234) 
# B is a 1-dimensional int32 tensor
B = tf.constant([123,456,789]) 
# C is a 2-dimensional int32 tensor
C = tf.constant([ [123,456,789], [222,333,444] ])

In [4]:
with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(A)
    print(output)

1234


In [5]:
x = tf.placeholder(tf.string)

with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Hello World'})
    print(output)

Hello World


In [6]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    output_x = sess.run(x, feed_dict={x: 'Test String', y: 123, z: 45.67})
    print(output_x)
    output_y = sess.run(y, feed_dict={x: 'Test String', y: 123, z: 45.67})
    print(output_y)
    output_z = sess.run(z, feed_dict={x: 'Test String', y: 123, z: 45.67})
    print(output_z)
    output = sess.run(tf.add(y,1), feed_dict={x: 'Test String', y: 123, z: 45.67})
    print(output)

Test String
123
45.66999816894531
124


In [7]:
def run():
    output = None
    x = tf.placeholder(tf.int32)

    with tf.Session() as sess:
        output = sess.run(x, feed_dict={x: 123})

    return output

print(run())

123


In [8]:
x = tf.add(5, 2)  # 7
y = tf.subtract(10, 4) # 6
z = tf.multiply(2, 5)  # 10

with tf.Session() as sess:
    # (z-y) + x*z
    output = sess.run(tf.add(tf.subtract(z, y),tf.multiply(x, z)))
    print(output)

74


In [9]:
x = tf.subtract(tf.cast(tf.constant(2.0), tf.int32), tf.constant(1))

with tf.Session() as sess:
    output = sess.run(x)
    print(output)

1


In [10]:
x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x,y),tf.cast(tf.constant(1), tf.float64))

with tf.Session() as sess:
    output = sess.run(z)
    print(output)

4.0


In [12]:
x = tf.Variable(5)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print(x)

Tensor("Variable_1/read:0", shape=(), dtype=int32)


In [14]:
n_features = 120
n_labels = 5
weights = tf.Variable(tf.truncated_normal((n_features, n_labels)))
print(weights)

Tensor("Variable_3/read:0", shape=(120, 5), dtype=float32)


In [15]:
n_labels = 5
bias = tf.Variable(tf.zeros(n_labels))
print(bias)

Tensor("Variable_4/read:0", shape=(5,), dtype=float32)


In [16]:
import numpy as np
t = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
u = np.array([1, 2, 3])
print(t + u)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [17]:
a = 1000000000
for i in range(1000000):
    a = a + 1e-6
print(a - 1000000000)

0.95367431640625
