In [1]:
import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.exp(x) / np.sum(np.exp(x), axis=0)

In [2]:
logits = [3.0, 1.0, 0.2]
print(softmax(logits))

[ 0.8360188   0.11314284  0.05083836]


In [3]:
logits = np.multiply([3.0, 1.0, 0.2], 10)
print(softmax(logits))

[  9.99999998e-01   2.06115362e-09   6.91440009e-13]


In [4]:
logits = np.divide([3.0, 1.0, 0.2], 10)
print(softmax(logits))

[ 0.38842275  0.31801365  0.2935636 ]


In [5]:
# logits is a two-dimensional array
logits = np.array([
    [1, 2, 3, 6],
    [2, 4, 5, 6],
    [3, 8, 7, 6]])
# softmax will return a two-dimensional array with the same shape
print(softmax(logits))

[[ 0.09003057  0.00242826  0.01587624  0.33333333]
 [ 0.24472847  0.01794253  0.11731043  0.33333333]
 [ 0.66524096  0.97962921  0.86681333  0.33333333]]


In [6]:
import tensorflow as tf

x = tf.nn.softmax([3.0, 1.0, 0.2])

In [7]:
with tf.Session() as sess:
    # Run the tf.constant operation in the session
    output = sess.run(x)
    print(output)

[ 0.83601874  0.11314283  0.05083835]
